-- ============================================================
-- 097 — Village Master duplicate rule = (District + Taluka + Village)
-- ============================================================
-- T-2026-114: Duplicate detection on the Village ('shivar') master is
-- widened from "village name only" to the composite of District + Taluka
-- + Village name. Same village name under a DIFFERENT taluka is now
-- allowed (e.g. "Wadali" under Akola/Balapur AND "Wadali" under Nashik/
-- Nashik-City are both valid rows). Same name under the SAME taluka is
-- rejected as duplicate.
--
-- WHERE THE RULE IS ENFORCED
-- --------------------------
-- The rule is enforced at the APPLICATION LAYER inside
-- `server/services/masters/management.js`:
--   • create(): for masterKey='shivar', findByLabel + findDeletedByLabel
--     are scoped by (parent_code = payload.parentCode) so a same-name
--     village under a different taluka does not trigger LABEL_TAKEN.
--   • update(): the label-taken re-check runs whenever the label OR the
--     parent_code changes, so moving a village from taluka A to taluka B
--     is properly validated against B's existing children (not A's).
--
-- WHY NOT A DB UNIQUE CONSTRAINT
-- ------------------------------
-- We deliberately do NOT add `UNIQUE(master_key, parent_code, label)` to
-- master_lookups because the current seed data (imported from the
-- Maharashtra government village CSV — see scripts/import-locations.js)
-- already contains multiple genuine (parent_code, label) duplicates.
-- These are historical seed artefacts, not admin-created errors. Adding
-- a UNIQUE index today would either
--   (a) fail the migration outright on any DB carrying those rows, or
--   (b) silently drop rows if the migration used INSERT IGNORE / DELETE
--       to reconcile — which the client explicitly forbids (spec: "the
--       migration must surface [violating rows] clearly rather than
--       silently drop rows").
--
-- The application-layer check prevents NEW duplicates while leaving the
-- historical rows intact. Admins can view and manually clean the
-- historical duplicates from the Masters admin UI if they wish.
--
-- CODE UNIQUENESS
-- ---------------
-- The existing `UNIQUE KEY uk_master_lookups_key_code (master_key, code)`
-- from migration 026 continues to enforce global-per-vocabulary code
-- uniqueness. Only the LABEL-duplicate rule is parent-scoped; the CODE
-- rule is untouched. New villages created via the "Other -> Save"
-- inline flow derive their code from the label (see codeFromLabel in
-- shared/components/LocationCascade.jsx) so an admin adding "Wadali"
-- twice under DIFFERENT talukas will produce two rows with codes like
-- "wadali" and "wadali-2" (the second is generated by the label->code
-- helper if the first slug is taken); if the admin supplies an explicit
-- code that collides, they get the standard CODE_TAKEN 409.
--
-- IDEMPOTENCY / SAFETY
-- --------------------
-- This migration performs NO schema change, NO INSERT, NO UPDATE, and
-- NO DELETE. It is a SELECT-only advisory that echoes the count of
-- pre-existing (parent_code, LOWER(label)) duplicate pairs so operators
-- can see the pre-existing seed exceptions at migrate time. Re-running
-- the migration is a pure no-op.
--
-- KNOWN PRE-EXISTING SEED DUPES (as of writing, in nasik_property_deals2)
-- ----------------------------------------------------------------------
--   parent_code | label       | count | parent taluka
--   4187        | Kailasnagar | 2     | Junnar
--   4246        | Malegaon    | 2     | Barshi
-- These 2 pairs (4 rows total) are historical Maharashtra CSV imports
-- with two distinct government codes each. They continue to hydrate
-- and select correctly through the FE cascade; the FE picks by code, so
-- ambiguity at the label level does not surface as a data-integrity
-- issue. Admins who wish to consolidate can pick one row and deactivate
-- the twin from the Masters admin.
-- ============================================================

SET NAMES utf8mb4;

-- Advisory count: emits the number of pre-existing (parent_code, label)
-- duplicate pairs so `npm run migrate` operators see the count in stdout.
-- The migration runner (`scripts/migrate.js`) runs SELECT statements and
-- discards their result rows; the count is visible in mysql-client
-- reruns of the same file if operators want to audit.
SELECT COUNT(*) AS pre_existing_village_duplicate_pairs
  FROM (
    SELECT parent_code, LOWER(label) AS lname
      FROM master_lookups
     WHERE master_key = 'shivar'
       AND deleted_at IS NULL
     GROUP BY parent_code, LOWER(label)
    HAVING COUNT(*) > 1
  ) dup;
