/**
 * Shared PDFKit-based export renderer for every admin module.
 *
 * Rewritten at T-2026-072 to match the enterprise "branded report" design
 * that used to be assembled client-side at T-2026-070. Now every export
 * comes off the backend, so the frontend never generates PDF content.
 *
 * Header:  logo mark + brand name + tagline + address + contact pills +
 *          report title + Export Date + Generated By  +  gradient rule
 * Body:    optional KPI summary cards row → optional "Filters Applied"
 *          chip block → paginated data table with #1A5E90 header, zebra
 *          rows, per-column alignment
 * Footer:  "Nasik Property Deals · Confidential"  |  "Page X of Y"  |
 *          "© YYYY Nasik Property Deals"   on every page
 *
 * Usage — all legacy calls still work; new fields are optional:
 *
 *   const buffer = await buildTablePdf({
 *     title:    'Inventory Properties Report',
 *     subtitle: '152 records',
 *     columns:  [{ label, key, weight, align?, noWrap?, headerAlign? }, ...],
 *     rows:     [{ [key]: value, ... }, ...],
 *     // NEW at T-2026-072:
 *     branding: {
 *       name: 'Nasik Property Deals',
 *       tagline: 'Premium Real Estate Management System',
 *       phone: '9876543210',
 *       altPhone: '',
 *       email: 'info@nasikpropertydeals.com',
 *       address: 'Near CBS, Nashik',
 *       website: 'www.nasikpropertydeals.com',
 *       gst: '',
 *     },
 *     exportedBy: 'Administrator',
 *     summaryCards: [{ label: 'Total Records', value: 152 }, ...],
 *     filterChips:  [{ label: 'District', value: 'Nashik' }, ...],
 *     emptyMessage: 'No records found for the selected filters.',
 *   });
 *
 * Unicode (Marathi / Hindi / Devanagari):
 * ---------------------------------------
 * Drop a `.ttf` at `server/assets/fonts/NotoSans-Regular.ttf` (and its bold
 * companion, plus Devanagari variants) to enable native rendering. See the
 * README at that path for exact filenames and download URLs. If the fonts
 * are missing the renderer falls back to PDFKit's built-in Helvetica and
 * Devanagari code points render as tofu boxes — the same behaviour as
 * before this upgrade, so nothing regresses on a fresh checkout.
 */

const PDFDocument = require('pdfkit');
const fs = require('fs');
const path = require('path');

// ─── Palette (matches T-2026-070's client-side design) ─────────────────────
const BRAND_PRIMARY    = '#1A5E90';
const BRAND_PRIMARY_DK = '#124465';
const BRAND_ACCENT     = '#daa13b';
const TEXT_INK   = '#0a1a33';
const TEXT_MUTED = '#6b7280';
const BORDER_SUBTLE = '#e5e7eb';
const ROW_ALT       = '#f7fafc';
const CARD_BG       = '#f5f8fb';
const ZEBRA         = '#fbfcfd';

// Legacy shim so old callers still get the same look (used by drawHeader
// when the new `branding` object isn't supplied).
const NAVY = BRAND_PRIMARY;
const GOLD = BRAND_ACCENT;
const GRAY_900 = TEXT_INK;
const GRAY_700 = '#29323e';
const GRAY_500 = TEXT_MUTED;
const GRAY_300 = '#c0c8d2';
const GRAY_100 = BORDER_SUBTLE;
const GRAY_50  = CARD_BG;

// ─── Font registration (Unicode-safe, graceful fallback) ───────────────────
//
// We look for user-supplied .ttf files in server/assets/fonts. If present,
// PDFKit uses them (needed for Devanagari); if absent, we stick with
// Helvetica so a fresh clone renders identically to the pre-upgrade state.
// One-time registration is memoised at module load so we don't stat the
// filesystem on every request.

const FONT_DIR = path.resolve(__dirname, '..', '..', 'assets', 'fonts');

function fontExists(filename) {
  try { return fs.existsSync(path.join(FONT_DIR, filename)); } catch { return false; }
}

const UNICODE_FONT_FILES = {
  regular: 'NotoSans-Regular.ttf',
  bold:    'NotoSans-Bold.ttf',
  // Devanagari support — Noto Sans Devanagari covers both Devanagari and
  // Latin so if only these two are present the whole document still renders.
  devRegular: 'NotoSansDevanagari-Regular.ttf',
  devBold:    'NotoSansDevanagari-Bold.ttf',
};

// Cache which font names are available per doc instance. Registration
// happens per doc because PDFKit tracks fonts internally on the doc.
function registerFonts(doc) {
  const regular = fontExists(UNICODE_FONT_FILES.regular)
    ? path.join(FONT_DIR, UNICODE_FONT_FILES.regular)
    : (fontExists(UNICODE_FONT_FILES.devRegular)
        ? path.join(FONT_DIR, UNICODE_FONT_FILES.devRegular) : null);
  const bold = fontExists(UNICODE_FONT_FILES.bold)
    ? path.join(FONT_DIR, UNICODE_FONT_FILES.bold)
    : (fontExists(UNICODE_FONT_FILES.devBold)
        ? path.join(FONT_DIR, UNICODE_FONT_FILES.devBold) : null);

  const map = {
    regular: 'Helvetica',
    bold: 'Helvetica-Bold',
  };
  try {
    if (regular) { doc.registerFont('Body',     regular); map.regular = 'Body'; }
    if (bold)    { doc.registerFont('BodyBold', bold);    map.bold    = 'BodyBold'; }
  } catch (_err) {
    // Fallthrough to Helvetica if the .ttf is corrupted / unreadable.
  }
  return map;
}

// ─── Public entrypoint ────────────────────────────────────────────────────

function buildTablePdf({
  title = 'Export',
  subtitle = '',
  columns,
  rows,
  brandName = 'Nasik Property Deals',
  pageSize = 'A4',
  landscape = true,
  // New at T-2026-072 — all optional so legacy callers still work.
  branding,
  exportedBy,
  summaryCards,
  filterChips,
  emptyMessage,
}) {
  if (!Array.isArray(columns) || columns.length === 0) {
    throw new Error('buildTablePdf: columns array is required');
  }
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({
      size: pageSize,
      layout: landscape ? 'landscape' : 'portrait',
      margin: 36,
      bufferPages: true,
    });

    const chunks = [];
    doc.on('data', (c) => chunks.push(c));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);

    const fonts = registerFonts(doc);

    drawBrandedHeader(doc, {
      fonts, title, subtitle, exportedBy,
      branding: normaliseBranding(branding, brandName),
    });

    if (Array.isArray(summaryCards) && summaryCards.length > 0) {
      drawSummaryCards(doc, { fonts, cards: summaryCards });
    }
    if (Array.isArray(filterChips) && filterChips.length > 0) {
      drawFilterChips(doc, { fonts, chips: filterChips });
    }

    drawTable(doc, { fonts, columns, rows: rows || [], emptyMessage });
    drawFooter(doc, {
      fonts,
      brandName: (branding && branding.name) || brandName,
    });

    doc.end();
  });
}

// ─── Header ────────────────────────────────────────────────────────────────

function normaliseBranding(b, fallbackName) {
  return {
    name: (b && b.name) || fallbackName || 'Nasik Property Deals',
    tagline: (b && b.tagline) || '',
    phone: (b && b.phone) || '',
    altPhone: (b && b.altPhone) || '',
    email: (b && b.email) || '',
    address: (b && b.address) || '',
    website: (b && b.website) || '',
    gst: (b && b.gst) || '',
  };
}

function drawBrandedHeader(doc, { fonts, title, subtitle, exportedBy, branding }) {
  const startX = 36;
  const startY = 36;
  const pageWidth = doc.page.width;
  const rightX = pageWidth - 36;
  const metaWidth = 220;
  const brandBlockWidth = pageWidth - 72 - metaWidth - 16;

  // ── Logo mark: a coloured disc with three ascending bar-graph shapes.
  //    Sized to match the brand mark used in the client-side design. If we
  //    ever ship a raster logo we can swap this for doc.image().
  drawLogoMark(doc, startX, startY, 56);

  // ── Brand block (left) ────────────────────────────────────────────────
  const brandTextX = startX + 56 + 12;
  let y = startY + 2;
  doc.fillColor(BRAND_PRIMARY).font(fonts.bold).fontSize(16)
    .text(branding.name, brandTextX, y, { width: brandBlockWidth, ellipsis: true });
  y = doc.y;
  if (branding.tagline) {
    doc.fillColor(TEXT_MUTED).font(fonts.regular).fontSize(9)
      .text(branding.tagline, brandTextX, y, { width: brandBlockWidth });
    y = doc.y;
  }
  if (branding.address) {
    doc.fillColor(TEXT_MUTED).font(fonts.regular).fontSize(8.5)
      .text(branding.address, brandTextX, y + 1, { width: brandBlockWidth });
    y = doc.y;
  }
  const contactBits = [];
  if (branding.phone)  contactBits.push('Tel ' + branding.phone + (branding.altPhone ? ' / ' + branding.altPhone : ''));
  if (branding.email)  contactBits.push(branding.email);
  if (branding.website) contactBits.push(branding.website);
  if (branding.gst)    contactBits.push('GSTIN ' + branding.gst);
  if (contactBits.length > 0) {
    doc.fillColor(BRAND_PRIMARY_DK).font(fonts.regular).fontSize(8)
      .text(contactBits.join('   ·   '), brandTextX, y + 2, { width: brandBlockWidth });
  }

  // ── Meta block (right) ────────────────────────────────────────────────
  const metaX = rightX - metaWidth;
  doc.fillColor(TEXT_INK).font(fonts.bold).fontSize(13)
    .text(title, metaX, startY + 2, { width: metaWidth, align: 'right' });
  const generatedAt = formatDateTime(new Date());
  doc.fillColor(TEXT_MUTED).font(fonts.regular).fontSize(8.5)
    .text('EXPORT DATE', metaX, doc.y + 4, { width: metaWidth, align: 'right' });
  doc.fillColor(TEXT_INK).font(fonts.bold).fontSize(9)
    .text(generatedAt, metaX, doc.y, { width: metaWidth, align: 'right' });
  doc.fillColor(TEXT_MUTED).font(fonts.regular).fontSize(8.5)
    .text('GENERATED BY', metaX, doc.y + 3, { width: metaWidth, align: 'right' });
  doc.fillColor(TEXT_INK).font(fonts.bold).fontSize(9)
    .text(exportedBy || 'Administrator', metaX, doc.y, { width: metaWidth, align: 'right' });

  // ── Gradient rule (navy → gold) ───────────────────────────────────────
  const ruleY = Math.max(doc.y, startY + 84) + 8;
  drawGradientRule(doc, startX, ruleY, pageWidth - 72);

  doc.y = ruleY + 10;

  // Legacy subtitle line (optional, e.g. "152 records · Admin-managed").
  if (subtitle) {
    doc.fillColor(TEXT_MUTED).font(fonts.regular).fontSize(9.5)
      .text(subtitle, startX, doc.y, { width: pageWidth - 72 });
    doc.y = doc.y + 2;
  }
}

function drawLogoMark(doc, x, y, size) {
  const cx = x + size / 2;
  const cy = y + size / 2;
  const r  = size / 2 - 2;
  // Outer accent ring
  doc.save();
  doc.circle(cx, cy, r).lineWidth(1.5).strokeColor(BRAND_ACCENT).stroke();
  // Inner filled disc
  doc.circle(cx, cy, r - 4).fill(BRAND_PRIMARY);
  // Three ascending bars
  const barWidth = 5;
  const barGap = 3;
  const totalBars = 3 * barWidth + 2 * barGap;
  const barsStartX = cx - totalBars / 2;
  const baseY = cy + 12;
  doc.fillColor('#ffffff');
  doc.rect(barsStartX,                              baseY - 12, barWidth, 12).fill();
  doc.rect(barsStartX + barWidth + barGap,          baseY - 18, barWidth, 18).fill();
  doc.rect(barsStartX + 2 * (barWidth + barGap),    baseY - 24, barWidth, 24).fill();
  doc.rect(barsStartX - 1, baseY, totalBars + 2, 1).fillOpacity(0.6).fill();
  doc.fillOpacity(1);
  doc.restore();
}

function drawGradientRule(doc, x, y, width) {
  // PDFKit has no gradient primitive on strokes; fake it with 60 slim slices.
  const steps = 60;
  const stepW = width / steps;
  for (let i = 0; i < steps; i += 1) {
    const t = i / (steps - 1);
    doc.rect(x + i * stepW, y, stepW + 0.5, 2.4).fill(interpColor(BRAND_PRIMARY, BRAND_ACCENT, t));
  }
}

function interpColor(a, b, t) {
  const ar = parseInt(a.slice(1, 3), 16), ag = parseInt(a.slice(3, 5), 16), ab = parseInt(a.slice(5, 7), 16);
  const br = parseInt(b.slice(1, 3), 16), bg = parseInt(b.slice(3, 5), 16), bb = parseInt(b.slice(5, 7), 16);
  const r = Math.round(ar + (br - ar) * t);
  const g = Math.round(ag + (bg - ag) * t);
  const bl = Math.round(ab + (bb - ab) * t);
  const hex = (n) => n.toString(16).padStart(2, '0');
  return `#${hex(r)}${hex(g)}${hex(bl)}`;
}

// ─── KPI summary cards ─────────────────────────────────────────────────────

function drawSummaryCards(doc, { fonts, cards }) {
  const startX = 36;
  const usable = doc.page.width - 72;
  const gap = 8;
  const maxCards = Math.min(cards.length, 6);
  const cardW = (usable - gap * (maxCards - 1)) / maxCards;
  const cardH = 42;
  const y = doc.y;

  for (let i = 0; i < maxCards; i += 1) {
    const x = startX + i * (cardW + gap);
    doc.save();
    doc.rect(x, y, cardW, cardH).fill('#ffffff');
    doc.rect(x, y, cardW, cardH).lineWidth(0.6).strokeColor(BORDER_SUBTLE).stroke();
    doc.rect(x, y, 3, cardH).fill(BRAND_PRIMARY);
    doc.fillColor(TEXT_MUTED).font(fonts.bold).fontSize(7)
      .text(String(cards[i].label || '').toUpperCase(), x + 8, y + 7, {
        width: cardW - 12, characterSpacing: 0.4,
      });
    doc.fillColor(TEXT_INK).font(fonts.bold).fontSize(14)
      .text(String(cards[i].value == null ? '' : cards[i].value), x + 8, y + 20, {
        width: cardW - 12, ellipsis: true,
      });
    doc.restore();
  }
  doc.y = y + cardH + 10;
}

// ─── Filters Applied block ─────────────────────────────────────────────────

function drawFilterChips(doc, { fonts, chips }) {
  const startX = 36;
  const usable = doc.page.width - 72;
  const items = chips.filter((c) => c && c.value !== '' && c.value != null);
  if (items.length === 0) return;
  const y = doc.y;

  // Compute the block height dynamically (chips wrap onto multiple rows).
  const chipHeight = 16;
  const chipGap = 4;
  const chipPadding = 8;
  const rowSpacing = 4;
  const labelWidth = (label) => Math.min(doc.widthOfString(String(label), { font: fonts.bold, size: 8 }), 80);
  const valueWidth = (value) => Math.min(doc.widthOfString(String(value), { font: fonts.bold, size: 8 }), 130);

  doc.font(fonts.bold).fontSize(8);
  const measured = items.map((c) => ({
    ...c,
    w: labelWidth(c.label) + 5 + valueWidth(c.value) + chipPadding * 2,
  }));

  // Draw the title strip.
  const titleH = 14;
  doc.fillColor(BRAND_PRIMARY_DK).font(fonts.bold).fontSize(8.5)
    .text('FILTERS APPLIED', startX + 10, y + 4, { characterSpacing: 0.4 });
  doc.rect(startX, y, usable, titleH + 4).lineWidth(0.4).strokeColor(BORDER_SUBTLE).stroke();

  let cursorY = y + titleH + 8;
  let cursorX = startX + 8;
  const rowMaxX = startX + usable - 8;

  for (const item of measured) {
    if (cursorX + item.w > rowMaxX) {
      cursorX = startX + 8;
      cursorY += chipHeight + rowSpacing;
    }
    // Chip pill
    doc.roundedRect(cursorX, cursorY, item.w, chipHeight, 3).fill(CARD_BG);
    doc.roundedRect(cursorX, cursorY, item.w, chipHeight, 3).lineWidth(0.5).strokeColor(BORDER_SUBTLE).stroke();
    doc.fillColor(TEXT_MUTED).font(fonts.bold).fontSize(8)
      .text(String(item.label) + ':', cursorX + chipPadding, cursorY + 3.5, {
        width: item.w - chipPadding * 2, lineBreak: false,
      });
    const labelW = labelWidth(item.label) + 5;
    doc.fillColor(TEXT_INK).font(fonts.bold).fontSize(8)
      .text(String(item.value), cursorX + chipPadding + labelW, cursorY + 3.5, {
        width: item.w - chipPadding * 2 - labelW, lineBreak: false, ellipsis: true,
      });
    cursorX += item.w + chipGap;
  }
  doc.y = cursorY + chipHeight + 8;
}

// ─── Data table ────────────────────────────────────────────────────────────

function drawTable(doc, { fonts, columns, rows, emptyMessage }) {
  const startX = 36;
  const usable = doc.page.width - 72;
  const widths = allocateWidths(columns, usable);

  drawHeaderRow(doc, { fonts, columns, widths, startX });

  if (!rows || rows.length === 0) {
    const y = doc.y;
    const h = 40;
    doc.rect(startX, y, usable, h).fill(ZEBRA);
    doc.rect(startX, y, usable, h).lineWidth(0.4).strokeColor(BORDER_SUBTLE).stroke();
    doc.fillColor(TEXT_MUTED).font(fonts.regular).fontSize(10)
      .text(emptyMessage || 'No records found for the selected filters.', startX, y + h / 2 - 6, {
        width: usable, align: 'center',
      });
    doc.y = y + h + 4;
    return;
  }

  for (let i = 0; i < rows.length; i += 1) {
    if (doc.y + 24 > doc.page.height - 56) {
      doc.addPage();
      drawHeaderRow(doc, { fonts, columns, widths, startX });
    }
    drawDataRow(doc, { fonts, columns, widths, startX, row: rows[i], stripe: i % 2 === 1 });
  }
}

function drawHeaderRow(doc, { fonts, columns, widths, startX }) {
  const rowY = doc.y;
  const rowHeight = 24;
  const totalWidth = widths.reduce((a, b) => a + b, 0);

  doc.rect(startX, rowY, totalWidth, rowHeight).fill(BRAND_PRIMARY);

  let x = startX;
  doc.font(fonts.bold).fontSize(9).fillColor('#ffffff');
  for (let i = 0; i < columns.length; i += 1) {
    const col = columns[i];
    doc.text(String(col.label || col.key || '').toUpperCase(), x + 6, rowY + 8, {
      width: widths[i] - 12,
      ellipsis: true,
      align: col.headerAlign || (col.align || 'left'),
      characterSpacing: 0.4,
    });
    x += widths[i];
  }

  doc.y = rowY + rowHeight;
}

function drawDataRow(doc, { fonts, columns, widths, startX, row, stripe }) {
  const rowY = doc.y;
  const totalWidth = widths.reduce((a, b) => a + b, 0);

  doc.font(fonts.regular).fontSize(9);
  let rowHeight = 20;
  for (let i = 0; i < columns.length; i += 1) {
    const col = columns[i];
    if (col.noWrap) continue;
    const text = stringify(row[col.key]);
    const h = doc.heightOfString(text, { width: widths[i] - 12 });
    if (h + 10 > rowHeight) rowHeight = Math.min(h + 10, 80);
  }

  if (stripe) {
    doc.rect(startX, rowY, totalWidth, rowHeight).fill(ROW_ALT);
  }

  let x = startX;
  for (let i = 0; i < columns.length; i += 1) {
    const col = columns[i];
    const text = stringify(row[col.key]);
    doc
      .fillColor(TEXT_INK)
      .font(fonts.regular)
      .fontSize(9)
      .text(text, x + 6, rowY + 6, {
        width: widths[i] - 12,
        ellipsis: true,
        lineBreak: col.noWrap ? false : true,
        height: rowHeight - 8,
        align: col.align || 'left',
      });
    x += widths[i];
  }

  doc
    .moveTo(startX, rowY + rowHeight)
    .lineTo(startX + totalWidth, rowY + rowHeight)
    .lineWidth(0.3)
    .strokeColor(BORDER_SUBTLE)
    .stroke();

  doc.y = rowY + rowHeight + 0.5;
}

// ─── Footer ────────────────────────────────────────────────────────────────

function drawFooter(doc, { fonts, brandName }) {
  const range = doc.bufferedPageRange();
  const year = new Date().getFullYear();
  for (let i = 0; i < range.count; i += 1) {
    doc.switchToPage(range.start + i);
    const y = doc.page.height - 28;
    const w = doc.page.width - 72;
    doc.font(fonts.regular).fontSize(8).fillColor(TEXT_MUTED);
    doc.text(`${brandName} · Confidential`, 36, y, { width: w, align: 'left' });
    doc.text(`Page ${i + 1} of ${range.count}`, 36, y, { width: w, align: 'center' });
    doc.text(`© ${year} ${brandName}`, 36, y, { width: w, align: 'right' });
  }
}

// ─── Small helpers ─────────────────────────────────────────────────────────

function allocateWidths(columns, usable) {
  const weights = columns.map((c) => Math.max(0.2, Number(c.weight) || 1));
  const total = weights.reduce((a, b) => a + b, 0);
  return weights.map((w) => Math.floor((w / total) * usable));
}

function stringify(value) {
  if (value === null || value === undefined) return '';
  if (value instanceof Date) return value.toLocaleString('en-IN');
  return String(value);
}

function formatDateTime(d) {
  const date = d instanceof Date ? d : new Date();
  return date.toLocaleString('en-IN', {
    day: '2-digit', month: 'short', year: 'numeric',
    hour: '2-digit', minute: '2-digit',
  });
}

function sendPdfResponse(res, { filename, buffer }) {
  res.setHeader('Content-Type', 'application/pdf');
  res.setHeader('Content-Disposition', `attachment; filename="${filename}"`);
  res.send(buffer);
}

module.exports = { buildTablePdf, sendPdfResponse };
